from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Literal, Optional, Tuple

import numpy as np
import torch
from torch.utils.data import Dataset
from tqdm import tqdm

from .transforms import build_image_transform


FMRI_AGG = Literal["mean", "first", "random"]

# Type alias: {subject_id: (mean_array, std_array)} both of shape (V,)
VoxelStats = Dict[int, Tuple[np.ndarray, np.ndarray]]


def discover_subjects(root: str | Path) -> List[int]:
    root = Path(root)
    subjects: List[int] = []
    for p in root.glob("sub-*"):
        m = re.match(r"sub-(\d+)", p.name)
        if m:
            subjects.append(int(m.group(1)))
    return sorted(subjects)


def split_exists(root: str | Path, split: str, subjects: Optional[List[int]] = None) -> bool:
    """Return True if the given split directory exists for every subject."""
    root = Path(root)
    if subjects is None:
        subjects = discover_subjects(root)
    for subj in subjects:
        split_dir = root / f"sub-{subj:02d}" / split
        if not split_dir.is_dir():
            return False
    return True


def _load_sample(path: Path) -> Dict[str, Any]:
    obj = np.load(path, allow_pickle=True)
    if hasattr(obj, "item"):
        return obj.item()
    raise ValueError(f"Unexpected npy payload at {path}")


def save_voxel_stats(stats: VoxelStats, path: str | Path) -> None:
    """Save per-voxel normalization statistics to a .pt file."""
    serialisable = {sid: (m.astype(np.float32), s.astype(np.float32)) for sid, (m, s) in stats.items()}
    torch.save(serialisable, path)


def load_voxel_stats(path: str | Path) -> VoxelStats:
    """Load per-voxel normalization statistics from a .pt file."""
    return torch.load(path, map_location="cpu", weights_only=False)


@dataclass
class NSDSample:
    image: torch.Tensor        # (3,H,W) float32 normalized
    fmri: torch.Tensor         # (V,) float32
    subject_id: int
    nsd_id: int
    coco_id: int
    labels: List[str]


class NSDProcessedDataset(Dataset):
    """Dataset for NSD-processed files generated by create_nsd.ipynb.

    Expected layout:
        root/sub-XX/{train|val|test}/sample_dict_<nsdId>.npy

    Per-voxel Z-score normalization (paper Appendix A.1):
        If *normalize* is True the dataset applies per-voxel Z-scoring.
        * When *voxel_stats* is **not** supplied the statistics are computed
          from this dataset (suitable for the **training** split).
        * When *voxel_stats* **is** supplied those statistics are re-used
          (suitable for val / test splits so they use the training mean/std).
    """

    def __init__(
        self,
        root: str | Path,
        split: str,
        subjects: Optional[Iterable[int]] = None,
        fmri_aggregation: FMRI_AGG = "mean",
        image_size: int = 224,
        normalize: bool = False,
        voxel_stats: Optional[VoxelStats] = None,
    ) -> None:
        self.root = Path(root)
        self.split = split
        self.fmri_aggregation: FMRI_AGG = fmri_aggregation
        self.transform = build_image_transform(image_size=image_size)
        self.normalize = normalize

        if subjects is None:
            subjects = discover_subjects(self.root)
            if not subjects:
                raise FileNotFoundError(f"No subject folders found under: {self.root}")
        self.subjects = [int(s) for s in subjects]

        self.files: List[Path] = []
        for subj in self.subjects:
            split_dir = self.root / f"sub-{subj:02d}" / split
            if not split_dir.exists():
                raise FileNotFoundError(f"Missing split dir: {split_dir}")
            self.files.extend(sorted(split_dir.glob("sample_dict_*.npy")))

        if not self.files:
            raise FileNotFoundError(
                f"No sample_dict_*.npy found under {self.root} for split={split} subjects={self.subjects}"
            )

        # Build subject->voxel_count cache by sampling the first file per subject
        self._subject_voxel_sizes: Dict[int, int] = {}
        for subj in self.subjects:
            subj_dir = self.root / f"sub-{subj:02d}" / split
            candidates = sorted(subj_dir.glob("sample_dict_*.npy"))
            if not candidates:
                continue
            d = _load_sample(candidates[0])
            
            # Get mask to count valid voxels
            mask = d.get("mask")
            if mask is None:
                raise KeyError(f"Missing 'mask' key in {candidates[0]}")
            mask = np.asarray(mask).astype(bool)
            v = int(mask.sum())  # count of True (valid) voxels
            self._subject_voxel_sizes[subj] = v

        # --- Per-voxel Z-score normalization ---
        if normalize:
            if voxel_stats is not None:
                self._voxel_stats: Optional[VoxelStats] = voxel_stats
            else:
                self._voxel_stats = self._compute_voxel_stats()
        else:
            self._voxel_stats = None

    # ------------------------------------------------------------------
    # Public helpers
    # ------------------------------------------------------------------

    @property
    def subject_voxel_sizes(self) -> Dict[int, int]:
        return dict(self._subject_voxel_sizes)

    @property
    def voxel_stats(self) -> Optional[VoxelStats]:
        """Return per-voxel (mean, std) for each subject, or None."""
        return self._voxel_stats

    def __len__(self) -> int:
        return len(self.files)

    def _process_fmri(self, fmri: np.ndarray, mask: np.ndarray) -> np.ndarray:
        """Process 4D fMRI: apply mask and aggregate across trials.
        
        Args:
            fmri: 4D fMRI data (R, X, Y, Z) where R = number of trials
            mask: 3D boolean mask (X, Y, Z). True = valid voxel to keep, False = exclude
        
        Returns:
            1D array (V,) of voxel activations after masking and trial aggregation
        """
        if fmri.ndim != 4:
            raise ValueError(f"Expected 4D fMRI (trial, X, Y, Z), got shape {fmri.shape}")
        if mask.ndim != 3:
            raise ValueError(f"Expected 3D mask (X, Y, Z), got shape {mask.shape}")
        
        # Ensure mask is boolean
        mask = mask.astype(bool)
        
        # Apply mask to each trial: (R, X, Y, Z) → (R, V)
        R = fmri.shape[0]
        fmri_2d = np.stack([fmri[r][mask] for r in range(R)], axis=0)  # (R, V)
        
        # Aggregate across trials
        if self.fmri_aggregation == "mean":
            return fmri_2d.mean(axis=0, dtype=np.float32)
        if self.fmri_aggregation == "first":
            return fmri_2d[0].astype(np.float32, copy=False)
        if self.fmri_aggregation == "random":
            ridx = np.random.randint(0, R)
            return fmri_2d[ridx].astype(np.float32, copy=False)
        raise ValueError(f"Unknown fmri_aggregation: {self.fmri_aggregation}")

    def __getitem__(self, idx: int) -> NSDSample:
        path = self.files[idx]
        d = _load_sample(path)

        image_np = np.asarray(d["image"])
        fmri_np = np.asarray(d["fmri"])  # (R, X, Y, Z) - 4D
        mask_np = np.asarray(d["mask"])  # (X, Y, Z) - 3D boolean
        
        # Apply mask and aggregate trials
        fmri_np = self._process_fmri(fmri_np, mask_np)  # → (V,)

        subject_id = int(d.get("subjectId"))
        nsd_id = int(d.get("nsdId"))
        coco_id = int(d.get("cocoId"))
        labels = list(d.get("label", []))

        image = self.transform(image_np).to(torch.float32)
        fmri = torch.from_numpy(fmri_np).to(torch.float32)

        return NSDSample(
            image=image,
            fmri=fmri,
            subject_id=subject_id,
            nsd_id=nsd_id,
            coco_id=coco_id,
            labels=labels,
        )


def collate_nsd(batch: List[NSDSample]) -> Dict[str, Any]:
    """Custom collate that stacks images but keeps variable-length fMRI as a list."""
    images = torch.stack([b.image for b in batch], dim=0)
    fmri = [b.fmri for b in batch]
    subject_ids = [b.subject_id for b in batch]
    nsd_ids = [b.nsd_id for b in batch]
    coco_ids = [b.coco_id for b in batch]
    labels = [b.labels for b in batch]
    return {
        "images": images,
        "fmri": fmri,
        "subject_ids": subject_ids,
        "nsd_ids": nsd_ids,
        "coco_ids": coco_ids,
        "labels": labels,
    }
